XXFLAGS =-ggdb -c -std=c++17 -Wpedantic -Wall -Wextra -Werror -Wzero-as-null-pointer-constant -Weffc++
CFLAGS=-std =c99 -pedantic -Wall -Wextra -Werror -ansi -Wwrite-strings


main: main.cpp
		echo     ------------compiling main.ccp to create executable program main----------------
		g++  -ggdb   -std=c++11   main.cpp   -o   main


clean:
		echo ----------------removing executable program main--------------------
		/bin/rm main
