XXFLAGS =-ggdb -c -std=c++17 -Wpedantic -Wall -Wextra -Werror -Wzero-as-null-pointer-constant
CFLAGS=-std =c99 -pedantic -Wall -Wextra -Werror -ansi -Wwrite-strings


main: testSortedList.cpp
		echo     ------------compiling testSortedList.ccp to create executable program main----------------
		g++  -ggdb   -std=c++11   testSortedList.cpp   -o   main


clean:
		echo ----------------removing executable program main--------------------
		/bin/rm main
